language:
- php
- node_js
php:
- 7.1
node_js: '6.11'
install:
- npm install
- composer install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
cache:
  directories:
  - node_modules
  - vendor
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
- nvm install
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^(qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
  - secure: OY56ebTjXs95OZ1tWKsh9nWcOZ1bo7lsapIADQyWjtDnfcE9u2swaAegKtMsx8qxIT/Czvjz31T4iVrWYZX/jzKezQE39lMyEkcZK3qmo1bRZhfeI7N890yV2YvLeOjL+1e1Ow72Q8UIrQnJ38wRcdTn8CWS6eTHdapMN/ZpMbtuWiapfax2eaGJ7xbjgKBOHqq544x98cosFQnVvkgfEouRor3HnzOsMZvPCDhfRQnzrAmHg48i1ggxTbMN34Z/97sMl5LBdxAot9Rsf447ZstkArdPn3INku5SJkI6XLozLZEKdFn5ZXmSdum/SEh00gH/asFh1a/OA2rNbyq4/aGsHRhuN2Nv2AYctTSLhyoGXfJI3hGF3XyHUOAznO+5LN/BdPXO+Jcj1Ad3PO3PW0bbBUV+A7q5uiugsEunf202EvVHzTxpTQp59EnXQ1Sa0srueXFMW4hdNsqet8bGNGq9FqbbNSFzRsIGIIix7ALpVryG5JLWmJcuuqo5DMG5NQnJIiGV4YBw4vQgfQctNp34IBhcQfx+tE+kPIe/puq/0vR5Ppgv9raa7D+C7NpUayn41C4g+/jQhx9K5v3QDeelxSv9aAqCxC3q4d+51dtU6LFCVh+hzgQXk6nD2INcT7MH56RuY8JxtgBJ095mSqOcVTp51CCQco1rNK/S+Rc=
